### ISSUE TITLE
Add Odor classification information page and populate it.

### ISSUE THREAD

**Issue by Bombergames** [noseplug/monorepo#1]
## Story/Task Details
- [ ] Make Odor Classification Activity and link it from map/context
- [ ] Create a visually pleasing way of helping users classify the odors using the classifications given by ATSDR

## Acceptance Scenarios
- Given: A user that has the app on the main page
- When: the user presses a button available on the main page (or context menu)
- Then: show the user a page helping them to classify the odor they smell

## Done Done Criteria
- [ ] Page can be easily navigated to and from using a clearly labeled or universally understandable button
- [ ]  Visually appealing
- [ ]  Verified by customer as having the correct and complete data

**Comment by crasm** [comment]
Merged and accepted
