### ISSUE TITLE
Rework registration activity

### ISSUE THREAD

**Issue by Bombergames** [noseplug/monorepo#2]
## Story/Task Details
- [ ] Update to fit the current user class
- [ ] Update to use the database interface
- [ ] Rework visuals to be a single scrollable with the most important information first
- [ ] Do not require optional information (Date of Birth, for example)
- [ ] add local variable to default to show registration page the first time it is needed (first comment or report)

## Acceptance Scenarios
- Given: A user who wants to create an account
- When: the user has started the app for the first time
- Then: Show registration page, let the user fill out the needed data, and register the user with the database interface

## Done Done Criteria
- [ ] Can create a user with the page
- [ ] Allows user to skip optional data and indicates the data is optional
- [ ] Automatically displays registration page on first report

**Comment by crasm** [comment]
Merged and accepted
