### ISSUE TITLE
Firebase Login and Registration

### ISSUE THREAD

**Issue by JinmingYu** [noseplug/monorepo#37]
## Story/Task Details
- research into firebase login and registration
- Integrate firebase to registration
- Integrate firebase to login

## Acceptance Scenarios
- the database is done
- When:
- should be able to create new accounts and validate an account

**Comment by crasm** [comment]
@estebanlau  I thought this was @JinmingYu's issue?

Anyway, the documentation suggests that there's a complete drop-in UI for auth:
1. https://firebase.google.com/docs/auth/?utm_source=studio
2. https://github.com/firebase/FirebaseUI-Android/tree/master/auth

**Comment by crasm** [comment]
afc52ace9434dcc998c02de4689032cc439ccfe7
