### ISSUE TITLE
Firebase Android Implementation: OdorEvents and OdorReports

### ISSUE THREAD

**Issue by Bombergames** [noseplug/monorepo#39]
## Story/Task Details
- [ ] OdorEvents and OdorReports can be created and fetched accurately from the database with no loss of data

## Acceptance Scenarios
- Given: The app
- When: You create an odor event with an odor report
- Then: It is stored on the database and accurately retrieved on next startup

## Done Done Criteria
All data is preserved for the odorevent and odorreport (comments will be a different issue), and they are properly loaded back in.

**Comment by crasm** [comment]
take a look at https://github.com/firebase/quickstart-android/blob/master/database/app/src/main/java/com/google/firebase/quickstart/database/NewPostActivity.java#L78

**Comment by crasm** [comment]
fddd4964be8c99d87ad4afb0b8a73b873a2dd7f0
