### ISSUE TITLE
Create Login Page

### ISSUE THREAD

**Issue by Bombergames** [noseplug/monorepo#6]
## Story/Task Details
- [ ] Create an activity that opens when the user has registered but is not logged in
- [ ] Use database interface to let the user log in
- [ ] Allow user to let device remember their login

## Acceptance Scenarios
- Given: A user with an account
- When: the user inputs the correct information
- Then: log the user in

## Done Done Criteria
- [ ] Login page is aesthetically pleasing
- [ ] Lets user login and responds appropriately to wrong data
- [ ] Passes user information to the rest of the application for use

**Comment by crasm** [comment]
Merged and accepted
