### ISSUE TITLE
Allow local officials to make announcements

### ISSUE THREAD

**Issue by Bombergames** [noseplug/monorepo#8]
## Story/Task Details
- [ ] Allow comments to be sticky
- [ ] Allow local officials to make a comment sticky when they make the comment
- [ ] Indicate in some way that the comment is sticky

## Acceptance Scenarios
- Given: A user logged in with status as a local official
- When: The user makes a comment on an odor event and checks a box
- Then: the comment should be "stickied" to the odor event, showing it above other comments. Sorting between stickied posts should be done so that the most recent are at the top.

## Done Done Criteria
- [ ] Only authorized users can make stickied comments
- [ ] Stickied comments show at the most prominent part of the comments box (probably the top)

**Comment by crasm** [comment]
4b0989238b5fe73bc0dcd051472901dfa04142a5
